development:
  sessions:
    default:
      database: boilerplate_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: boilerplate_dev
      hosts:
        - localhost:27017

# heroku config:set MONGOHQ_URL=mongodb://heroku@<YOUR_URL>
<% if ENV['MONGOHQ_URL'] %>
  <% uri = URI.parse(ENV['MONGOHQ_URL']) %>
production:
  <<: *defaults
  sessions:
    default:
      <<: *default_session
      database: <%= uri.path.sub('/','') %>
      username: <%= uri.user %>
      password: <%= uri.password %>
      hosts:
        - <%= uri.host %>:<%= uri.port %>
<% end %>